name: build-docker

on: 
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read & Increment Version
        id: get_version
        run: |
          if [ ! -f version.txt ]; then
            echo "1.0.0" > version.txt
          fi

          latest_version=$(cat version.txt)
          major=$(echo $latest_version | cut -d. -f1)
          minor=$(echo $latest_version | cut -d. -f2)
          patch=$(echo $latest_version | cut -d. -f3)

          new_version="$major.$minor.$((patch+1))"
          echo "$new_version" > version.txt

          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "New Version: $new_version"

      - name: Commit new version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add version.txt
          git commit -m "Bump version to ${{ env.new_version }}"
          git push origin main

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            alexis341/my-app-getting:latest
            alexis341/my-app-getting:${{ env.new_version }}
            alexis341/my-app-getting:${{ github.sha }}
